### ISSUE TITLE
Kopia doesn't start again when repository is added

### ISSUE THREAD

**Issue by x80486** [flathub/io.kopia.KopiaUI#1]
I just start the application, add a new `Filesystem` repository (USB hard drive)...and if I close the application and try to open it up again, it fails to start:

```shell
[x80486@archbook:~]$ flatpak run io.kopia.KopiaUI 
Gtk-Message: 09:28:26.306: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:28:26.306: Failed to load module "canberra-gtk-module"
09:28:26.457 › errorTypeError: app.isInApplicationsFolder is not a function
09:28:26.460 › APPIMAGE env is not defined, current application is not an AppImage
[x80486@archbook:~]$ [fake-sandbox: zypak-sandbox] No data could be read (host died?)
[fake-sandbox: zypak-sandbox] Quitting Zygote...

[x80486@archbook:~]$ ps -ax | grep kopia 
 145761 ?        S      0:00 bwrap --args 34 kopia-ui
 145775 ?        S      0:00 bwrap --args 34 kopia-ui
 145776 ?        Sl     0:02 /app/KopiaUI/kopia-ui
 145780 ?        S      0:00 /app/KopiaUI/chrome-sandbox /app/KopiaUI/kopia-ui --type=zygote
 145803 ?        Sl     0:00 /app/KopiaUI/kopia-ui --type=gpu-process --field-trial-handle=12007952711933511166,3324977905425414712,131072 --disable-features=SpareRendererForSitePerProcess --gpu-preferences=KAAAAAAAAAAgAAAgAAAAAAAAYAAAAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=11610396510170346263
 145808 ?        Sl     0:03 /app/KopiaUI/resources/server/kopia server --ui --random-password --tls-generate-cert --address=localhost:0
 146772 pts/7    S+     0:00 grep --color=auto kopia
```

I have the latest version installed and I'm running Arch Linux `Linux uplink 5.4.54-1-lts #1 SMP Wed, 29 Jul 2020 21:38:41 +0000 x86_64 GNU/Linux`.

**Comment by darkdragon-001** [comment]
I think I have seen this behavior before  and will investigate more on the weekend.

It might be the same as flathub/org.nextcloud.Nextcloud#17 (at least running `ps` showed me it did not exit correctly and multiple versions are running). 

The packaging is quite similar to Riot/Element and Signal messenger Flathub package. Does the problem appear for these apps as well? 

The app is based on the Debian/apt package. Does Kopia show the same behavior for the `deb` or `appimage` packages?

**Comment by x80486** [comment]
The AppImage doesn't run for me (needs some additional libraries), although I can test it on a different operating system.

I use Signal and Element, but I haven't seen this behavior with those so far — although Signal was _choking_ yesterday sometimes, but it's probably unrelated.

**Comment by darkdragon-001** [comment]
I can check the AppImage myself on the weekend if it is too much hassle for you... 

The Flatpak version is started with the following script (same as Element/Signal):
```
export TMPDIR="$XDG_RUNTIME_DIR/app/$FLATPAK_ID"
exec zypak-wrapper /app/KopiaUI/kopia-ui "$@"
```

Probably I have to do more research about the zypak-wrapper... Maybe it is possible to run non-flatpak versions with it too for easier debugging?

**Comment by darkdragon-001** [comment]
I just checked with v0.6.0-rc4 (#3) and it doesn't show the behavior on my machine. @x80486 Can you please check with this version?

**Comment by x80486** [comment]
...let me check :+1:

**Comment by x80486** [comment]
Damn right! The issue is gone now. I tried a couple of times and it always starts correctly. Thanks for fixing it :cake: :tropical_drink:

You might want to reference the issue number in the pull request, so it gets closed automatically when merged.
