### ISSUE TITLE
0.12.1 not being published?

### ISSUE THREAD

**Issue by sfalken** [flathub/io.kopia.KopiaUI#18]
Current release version is 0.12.1, released 1-Oct-22, but the version being published on flathub in the stable repo is 0.10.7, released 6-Apr-22

I see in the .json that you've indeed updated to be building 0.12.1, but it doesn't appear to be being published out to the flathub repo.

I'd offer to help, but I don't even know where I would start.

**Comment by darkdragon-001** [comment]
How do you come to the conclusion that the version published on Flathub is 0.10.7? For me it shows 0.12.1: https://flathub.org/apps/details/io.kopia.KopiaUI

Also when starting the app, it shows me 
> Version v0.12.1 5227d74996b6520f9f96e4203cfe00b832a60d5f kopia/htmlui 5cbe5f7147f27729adce475f2774926933ede250 built on Wed Sep 28 04:26:24 UTC 2022 fv-az39-946

**Comment by sfalken** [comment]
Well would you look at that.

Sorry for the waste of a bug report.   Looks like this is a Discover issue, and not a flatpak/flathub/or kopia issue.
Both screenshots from same system.
![Screenshot_20230227_151531](https://user-images.githubusercontent.com/95936027/221711402-addb55fd-9517-4190-a0c1-d0f5ba9f5d53.png)
![Screenshot_20230227_151944](https://user-images.githubusercontent.com/95936027/221711484-18a0a3dc-bf4b-44d8-a35d-a2054ed97ca3.png)

**Comment by darkdragon-001** [comment]
Thanks for letting me know. This seems to be an issue which the AppStream manifest: https://github.com/flathub/io.kopia.KopiaUI/blob/dc476738a36ec5e47e7a8a74cffd7f7cf6901e68/io.kopia.KopiaUI.appdata.xml#L22-L28.
Multiple versions can be included there. I think the latest date should be chosen. But instead it seems to string sort the versions and the first one included a "v" prefix so is sorted last and assumed to be the latest one. I will check back the AppStream documentation and probably just delete the first entry. Probably you should file a bug for Discover as well.

**Comment by darkdragon-001** [comment]
I checked the [specification](https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Releases.html#spec-releases) and it tells to sort latest-to-oldest which I did. The [version comparison algorithm](https://www.freedesktop.org/software/appstream/docs/chap-AppStream-Misc.html#spec-vercmp-algorithm) should sort letters before numbers, so this should still lead to the desired result. Please file a bug at KDE Discover.
