### ISSUE TITLE
Please update to stable release v0.13.0

### ISSUE THREAD

**Issue by justanothergithubuserNr2** [flathub/io.kopia.KopiaUI#25]
Since 2 weeks a stable version of v0.13.0 is available:

https://github.com/kopia/kopia/releases

Current release here on Flathub: 0.13.0-rc2

**Comment by darkdragon-001** [comment]
The automated build failed in #24. I fixed and published it manually and it should be on Flathub soon. Please comment if something doesn't work.

In the future, only stable releases should be used for Flathub as of #28. Please open an issue in case future releases don't appear!
