### ISSUE TITLE
Creating a storage config: rclone executable not found

### ISSUE THREAD

**Issue by andmalc** [flathub/io.kopia.KopiaUI#43]
I'm attempting to add a remote storage configuration for an existing and working configured remote.  In the Storage Configuration screen I enter the remote name and the rclone host path `/usr/bin/rclone`.  When I click Next this error appears:

`Connect Error: INTERNAL: internal server error: unable to start rclone: fork/exec /usr/bin/rclone: no such file or directory`

Flatseal shows under Filesystem / All system libraries, executables and static data /  filesystem=host-os.  I also tried running:

` flatpak run app/io.kopia.KopiaUI/x86_64/master --filesystem=/usr/bin/rclone`

This is a fresh install of KopiaUI v 0.15.0 on Fedora 39.  I also tried building the app from source using flatpak-builder.

**Comment by ImBearChild** [comment]
I have made a pull request for this, and you may want to give it a try. You can download the test build from the flathub bot.

https://github.com/flathub/io.kopia.KopiaUI/pull/48#issuecomment-2143842875
